// react/m-app-test/src/components/List.js
import React, { Component } from 'react'
import { connect } from 'react-redux'
import { withRouter } from 'react-router-dom'
import Api from '../api'
import actionCreator from '../store/actionCreator'
import LazyLoad from 'react-lazy-load'

class List extends Component {
  //详情
  handleDetail(id) {
    this.props.history.push(`/index/detail/${id}`)
  }
  //收藏
  handleAdd(item) {
    let { myBook, currentId } = this.props
    item.count = 1
    item.checked = true
    myBook.push(item)
    this.props.setState('myBook', myBook)
    this.props.setState('loading', true)
    Api.add({ book: item }).then(res => {
      if (res.code === 200) {
        //收藏成功后再获取一遍列表数据，把收藏变成已收藏
        this.props.onDispacth(actionCreator.getList(currentId))
      }
    })
  }
  render() {
    let { currentList } = this.props
    //is_in_my_book标识收藏和已收藏，true为已收藏，false为收藏
    let currentListDom = currentList.map(item => (
      <div key={item.id} className="m-list-item">
        <LazyLoad className="m-list-item-img-wrap">
          <img src={item.avatar} className="m-list-item-img"></img>
        </LazyLoad>
        <div className="m-list-item-info">
          {item.title}
          <button onClick={this.handleDetail.bind(this, item.id)}>详情</button>
          {
            item.is_in_my_book ?
              <button>已收藏</button>
              :
              <button onClick={this.handleAdd.bind(this, item)}>收藏</button>
          }
        </div>
      </div>
    ))
    return (
      <div>
        {currentListDom}
      </div>
    )
  }
}

const mapStateToProps = (state) => {
  return {
    navList: state.navList,
    currentId: state.currentId,
    currentList: state.currentList,
    myBook: state.myBook
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    setState(key, value) {
      dispatch({ type: 'SET_STATE', key, value })
    },
    onDispacth(action) {
      dispatch(action)
    }
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(withRouter(List))

// m-book/src/components/List.vue
<template>
  <div>
    <div v-for="item in currentList" :key="item.id" class="m-list-item">
      <div class="m-list-item-img-wrap">
        <img v-lazy="item.avatar" alt="" class="m-list-item-img">
      </div>
      <div class="m-list-item-info">
        <div>{{item.title}}</div>
        <div>
          <button @click="handleDetail(item.id)">详情</button>
          <button v-if="item.is_in_my_book">已收藏</button>
          <button v-else @click="handleAdd(item)">收藏</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Api from '../api'

export default {
  computed: {
    currentList() {
      return this.$store.state.currentList
    }
  },
  methods: {
    handleAdd(book) {
      if (!localStorage.getItem('username')) {
        this.$router.push('/login')
      }
      book.count = 1
      book.checked = true
      Api.add({book}).then(res => {
        if (res.code === 200) {
          this.$store.dispatch({ type: 'getList' })
        }
      })
    },
    handleDetail(id) {
      //this.$router.push(`/detail/${id}`)
      this.$router.push({ path: '/detail', query: { id }})
    }
  }
}
</script>

<style>

</style>
