// m-book/src/components/Nav.vue
<template>
  <div class="m-nav-warp">
    <div
      v-for="item in navList"
      :key="item.id"
      class="m-nav-item"
      :class="{active: currentId === item.id}"
      @click="handleNav(item.id)"
    >{{item.title}}</div>
  </div>
</template>

<script>
export default {
  computed: {
    navList() {
      return this.$store.state.navList;
    },
    currentId() {
      return this.$store.state.currentId;
    }
  },
  methods: {
    handleNav(id) {
      this.$store.commit({ type: 'setState', key: 'currentId', value: id })
      document.getElementById(id).scrollIntoView(true)
    }
  }
};
</script>

<style>
</style>

// react/m-app/src/components/Nav.js
import React, { Component } from 'react'
import { connect } from 'react-redux'
import actionCreator from '../store/actionCreator'

class Nav extends Component {
  handleNav(id) {
    this.props.setState('currentId', id)
    //this.props.dispatch(actionCreator.getList(id))
  }
  componentDidMount() {
    let { currentId } = this.props
    actionCreator.getList(currentId)
    //this.props.dispatch(actionCreator.getList(currentId))
  }
  render() {
    let { navList, currentId } = this.props
    let navListDom = navList.map(item => (
      <span 
        key={item.id} 
        className={'m-nav-item ' + (currentId === item.id ? 'active' : '')} 
        onClick={this.handleNav.bind(this, item.id)}>{item.title}</span>
    ))
    return (
      <div>
        {navListDom}
      </div>
    )
  }
}

const mapStateToProps = (state) => {
  return {
    navList: state.navList,
    currentId: state.currentId
  }
}

const mapDispatchToProps = (dispatch) => {
  return ({
    setState(key, value) {
      dispatch({ type: 'SET_STATE', key, value })
    },
    onDispatch(action) {
      dispatch(action)
    }
  })
}

export default connect(mapStateToProps, mapDispatchToProps)(Nav)
