// react/react书包/src/view/Login.js
import React, { Component } from 'react'
import Api from '../api'

class Login extends Component {
  constructor(props) {
    super(props)
    this.state = {
      username: '',
      password: ''
    }
  }

  handleInput(field, e) {
    this.setState({
      [field]: e.target.value
    })
  }

  handleLogin() {
    let { username, password } = this.state
    if (username.trim() === '') {
      alert('用户名不能为空')
      return
    }
    if (password.trim() === '') {
      alert('密码不能为空')
      return
    }
    Api.login({ username, password }).then(res => {
      if (res.code === 200) {
        this.props.history.push('/index/home')
      }
    })
  }

  handleEnter(e) {
    if (e.keyCode === 13) {
      this.handleLogin()
    }
  }

  render() {
    let { username, password } = this.state
    return (
      <div>
        <div>
          <input value={username} onChange={this.handleInput.bind(this, 'username')} autoFocus placeholder="请输入用户名"></input>
        </div>
        <div>
          <input value={password} onChange={(e) => this.handleInput('password', e)} onKeyUp={this.handleEnter.bind(this)} placeholder="请输入密码" type="password"></input>
        </div>
        <button onClick={this.handleLogin.bind(this)}>登录</button>
      </div>
    )
  }
}
export default Login

// m-friends/src/views/Login.vue
<template>
  <div>
    <div>
      <input v-model="username" placeholder="请输入用户名" ref="username" />
    </div>
    <div>
      <input
        v-model="password"
        placeholder="请输入密码"
        :type="isShow ? 'text' : 'password'"
        @keyup.enter="handleLogin()"
      />
      <span
        :class="'icon iconfont m-input-icon ' + (isShow ? 'icon-caozuo-xianshihaoma' : 'icon-buxianshimima')"
        @click="handlePassword()"
      ></span>
    </div>

    <button @click="handleLogin()">登录</button>
    <router-link to="/register">注册</router-link>
  </div>
</template>

<script>
import Api from "../api";

export default {
  data() {
    return {
      username: "admin",
      password: "123456",
      isShow: false
    };
  },
  methods: {
    handleLogin() {
      if (this.username.trim() === "") {
        alert("用户名不能为空");
        return;
      }
      if (this.password.trim() === "") {
        alert("密码不能为空");
        return;
      }
      Api.login({ username: this.username, password: this.password }).then(
        res => {
          if (res.code === 200) {
            localStorage.setItem("token", res.data.token);
            localStorage.setItem('username', res.data.username)
            this.$router.push("/index/home");
          }
        }
      );
    },
    handlePassword() {
      this.isShow = !this.isShow;
    }
  },
  mounted() {
    this.$refs.username.focus();
  }
};
</script>

<style>
</style>
