// react/m-app/src/view/Home.js
import React, { Component } from 'react'
import Nav from '../components/Nav'
import List from '../components/List'
import { connect } from 'react-redux'

class Home extends Component {
  render() {
    return (
      <div>
        <Nav></Nav>
        <List></List>
      </div>
    )
  }
}

const mapStateToProps = (state) => {
  return {

  }
}

const mapDispatchToProps = (dispatch) => {
  return ({
    setState(key, value) {
      dispatch({ type: 'SET_STATE', key, value })
    }
  })
}

export default connect(mapStateToProps, mapDispatchToProps)(Home)

// m-book/src/views/Home.vue
<template>
  <div class="m-home">
    <Nav></Nav>
    <List></List>
  </div>
</template>

<script>
import Nav from '../components/Nav'
import List from '../components/List'

export default {
  components: {
    Nav,
    List
  },
  mounted() {
    this.$store.dispatch({ type: 'getNav' })
    this.$store.dispatch({ type: 'getList' })
    this.$store.dispatch({ type: 'getListAll' })
  }
}
</script>

<style>

</style>
