// react/m-app-test/src/components/Nav.js
import React, { Component } from 'react'
import { connect } from 'react-redux'
import Api from '../api'
import actionCreator from '../store/actionCreator'

class Nav extends Component {
  handleNav(id) {
    this.props.setState('currentId', id)
    this.props.onDispacth(actionCreator.getList(id))
  }
  componentDidMount() {
    let { currentId } = this.props
    this.props.onDispacth(actionCreator.getNav())
    this.props.onDispacth(actionCreator.getList(currentId))
  }
  render() {
    let { navList, currentId } = this.props
    let navListDom = navList.map(item => (
      <span 
        key={item.id} 
        className={"m-nav-item " + (currentId === item.id ? 'active' : '')}
        onClick={this.handleNav.bind(this, item.id)}>{item.title}</span>
    ))
    return (
      <div>
        {navListDom}
      </div>
    )
  }
}

const mapStateToProps = (state) => {
  return {
    navList: state.navList,
    currentId: state.currentId
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    setState(key, value) {
      dispatch({ type: 'SET_STATE', key, value })
    },
    onDispacth(action) {
      dispatch(action)
    }
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(Nav)

// 书包（楼层）/前端/src/components/Nav.vue
<template>
  <div class="m-nav">
    <div
      v-for="item in list"
      :key="item.id"
      class="m-sidebar-item"
      :class="{ active: currentId === item.id }"
      @click="handleNav(item.id)"
    >{{item.title}}</div>
  </div>
</template>

<script>
export default {
  computed: {
    list() {
      return this.$store.state.list;
    },
    currentId() {
      return this.$store.state.currentId
    }
  },
  methods: {
    handleNav(id) {
      this.$store.commit({ type: 'setState', key: 'currentId', value: id })
      //https://developer.mozilla.org/zh-CN/docs/Web/API/Element/scrollIntoView
      document.getElementById(id).scrollIntoView(true)
    }
  }
};
</script>

<style>
</style>
