// m-book/src/views/Detail.vue
<template>
  <div>
    <img :src="detail.avatar" alt />
    <div>
      <button v-if="detail.is_in_my_book">已收藏</button>
      <button v-else @click="handleAdd(detail)">收藏</button>
    </div>
    <div>{{detail.summary}}</div>
  </div>
</template>

<script>
import Api from "../api";

export default {
  data() {
    return {
      detail: {}
    };
  },
  methods: {
    handleAdd(book) {
      if (!localStorage.getItem("username")) {
        this.$router.push("/login");
      }
      book.count = 1;
      book.checked = true;
      Api.add({ book }).then(res => {
        if (res.code === 200) {
          this.detail.is_in_my_book = true;
        }
      });
    }
  },
  mounted() {
    let { id } = this.$route.query;
    Api.getDetail(`?id=${id}`).then(res => {
      if (res.code === 200) {
        this.detail = res.data;
      }
    });
  }
};
</script>

<style>
</style>

// react/m-app-test/src/view/Detail.js
import React, { useState, useEffect } from 'react'
import { connect } from 'react-redux'
import Api from '../api'

const Detail = (props) => {
  const [detail, setDetail] = useState({})

  const handleAdd = (item) => {
    let { myBook } = props
    item.count = 1
    item.checked = true
    myBook.push(item)
    props.setState('myBook', myBook)
    //显示loading
    Api.add({ book: item }).then(res => {
      if (res.code === 200) {
        //取消loading
        item.is_in_my_book = true
        let itemClone = JSON.parse(JSON.stringify(item))
        setDetail(itemClone)
      }
    })
  }

  useEffect(() => {
    let { id } = props.match.params
    props.setState('loading', true)
    Api.getDetail(`?id=${id}`).then(res => {
      if (res.code === 200) {
        setDetail(res.data)
        props.setState('loading', false)
      }
    })
  }, [])

  return (
    <div>
      <img src={detail.avatar}></img>
      {detail.title}
      {
        detail.is_in_my_book ?
          <button>已收藏</button>
          :
          <button onClick={handleAdd.bind(this, detail)}>收藏</button>
      }

    </div>
  )
}

const mapStateToProps = (state) => {
  return {
    myBook: state.myBook
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    setState(key, value) {
      dispatch({ type: 'SET_STATE', key, value })
    }
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(Detail)
