// 书包（楼层）/前端/src/views/Home.vue
<template>
  <div class="m-main">
    <div class="m-home">
      <Nav></Nav>
      <List></List>
    </div>
  </div>
</template>

<script>
import Nav from "../components/Nav";
import List from "../components/List";

export default {
  components: {
    Nav,
    List
  },
  //挂载完，刷新时
  mounted() {
    this.$store.dispatch({ type: "getList" });
  }
};
</script>

<style>
</style>

// react/m-app-test/src/view/Home.js
import React, { Component } from 'react'
import Nav from '../components/Nav'
import List from '../components/List'
import { BackTop, Button } from 'antd'

export default class Home extends Component {
  render() {
    return (
      <div>
        <Nav></Nav>
        <List></List>
        <BackTop>回到顶部</BackTop>
      </div>
    )
  }
}
