// m-book/src/views/Home.vue
<template>
  <div class="m-home">
    <Nav></Nav>
    <List></List>
  </div>
</template>

<script>
import Nav from '../components/Nav'
import List from '../components/List'

export default {
  components: {
    Nav,
    List
  },
  mounted() {
    this.$store.dispatch({ type: 'getNav' })
    this.$store.dispatch({ type: 'getList' })
    this.$store.dispatch({ type: 'getListAll' })
  }
}
</script>

<style>

</style>

// react/m-app-test/src/view/Home.js
import React, { Component } from 'react'
import Nav from '../components/Nav'
import List from '../components/List'
import { BackTop, Button } from 'antd'

export default class Home extends Component {
  render() {
    return (
      <div>
        <Nav></Nav>
        <List></List>
        <BackTop>回到顶部</BackTop>
      </div>
    )
  }
}
